# Generated by Django 5.2.7 on 2025-10-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_is_admin_customuser_is_admin_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin_user',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_normal_user',
            new_name='is_recruiter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
