# Generated by Django 5.2.7 on 2025-10-12 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_category', models.CharField(choices=[('IT', 'Information Technology'), ('Mechanical', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('Electrical', 'Electrical Engineering'), ('Electronics', 'Electronics Engineering'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=100)),
                ('job_location', models.CharField(max_length=150)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
