# Generated by Django 5.2.7 on 2025-10-12 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_jobpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
