# Generated by Django 5.2.7 on 2025-10-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_jobpost_options_remove_jobpost_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
