# Generated by Django 5.2.7 on 2025-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_civiljobs_posted_on_civiljobs_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(choices=[('IT', 'IT'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Other', 'Other')], max_length=100),
        ),
    ]
