# Generated by Django 5.2.7 on 2025-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_jobapplication_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
