# Generated by Django 5.2.7 on 2025-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_jobapplication_job_location_jobapplication_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiljobs',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itjobs',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mechjobs',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
