# Generated by Django 5.2.7 on 2025-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_civiljobs_salary_alter_itjobs_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
