# Generated by Django 5.2.7 on 2025-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_customuser_bio_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
