# Generated by Django 5.2.7 on 2025-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_jobapplication_ai_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
    ]
