# Generated by Django 5.2.7 on 2025-12-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_jobapplication_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='civiljobs',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (python, django, sql)', null=True),
        ),
        migrations.AddField(
            model_name='itjobs',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (python, django, sql)', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (python, django, sql)', null=True),
        ),
        migrations.AddField(
            model_name='mechjobs',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (python, django, sql)', null=True),
        ),
    ]
