# Generated by Django 5.2.7 on 2025-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_civiljobs_required_skills_itjobs_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='matched_skills',
            field=models.TextField(blank=True, help_text='Skills matched from resume', null=True),
        ),
    ]
