# Generated by Django 5.2.7 on 2025-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_jobapplication_ai_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
