# Generated by Django 5.2.7 on 2025-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_jobapplication_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description_snapshot',
            field=models.TextField(blank=True, help_text='Job description at the time of application', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_id',
            field=models.PositiveIntegerField(default=0, help_text='ID of the job from IT / Mechanical / Civil table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='required_skills_snapshot',
            field=models.TextField(blank=True, help_text='Required skills at the time of application', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ai_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI generated resume summary', null=True),
        ),
    ]
