# Generated by Django 5.2.7 on 2025-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_jobapplication_job_description_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the job from IT / Mechanical / Civil table', null=True),
        ),
    ]
