# Generated by Django 5.2.7 on 2025-12-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_alter_jobapplication_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiljobs',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (structural analysis, critical thinking, project management, Construction Knowledge)', null=True),
        ),
        migrations.AlterField(
            model_name='mechjobs',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills (design, develop, build, mechanical engineer, CAD)', null=True),
        ),
    ]
