# Generated by Django 5.2.7 on 2025-12-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_alter_civiljobs_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
