# Generated by Django 5.2.7 on 2025-12-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_jobapplication_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
    ]
