# Generated by Django 5.2.7 on 2025-12-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_remove_jobapplication_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
